version: "3.9"

services:
  jekyll-theme:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/site
      - bundle_cache:/usr/local/bundle
    command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --incremental --force_polling"

volumes:
  bundle_cache:
